# Generated by Django 4.1.2 on 2023-01-11 12:58

from django.db import migrations, models
import otp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('expiration_time', models.DateTimeField()),
                ('code', models.CharField(max_length=6)),
            ],
        ),
    ]
