# Generated by Django 4.1.2 on 2023-01-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_last_update_product_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='placed_at',
            new_name='created_at',
        ),
    ]
