# Generated by Django 4.1.2 on 2023-01-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_placed_at_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='parent_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.collection'),
        ),
    ]
