# Generated by Django 4.1.2 on 2023-02-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productimage'),
        ('store', '0007_alter_order_status_orderstatuslog'),
    ]

    operations = [
    ]
