# Generated by Django 4.1.2 on 2023-02-10 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_merge_20230210_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderstatuslog',
            name='status',
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='current_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Completed'), (3, 'Canceled'), (4, 'Failed')], default=0),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='performer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='previous_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Completed'), (3, 'Canceled'), (4, 'Failed')], default=0),
        ),
    ]
