# Generated by Django 4.1.2 on 2023-02-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_status_remove_orderstatuslog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatuslog',
            name='current_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Awaiting Fulfillment'), (4, 'Partially Fulfilled'), (5, 'Fulfilled'), (6, 'Shipped'), (7, 'Out For Delivery'), (8, 'Delivered'), (9, 'Cancelled'), (10, 'Refunded'), (11, 'On Hold'), (12, 'Returned'), (13, 'Exchange Requested'), (14, 'Completed'), (15, 'Dispute')], default=1),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='previous_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Awaiting Fulfillment'), (4, 'Partially Fulfilled'), (5, 'Fulfilled'), (6, 'Shipped'), (7, 'Out For Delivery'), (8, 'Delivered'), (9, 'Cancelled'), (10, 'Refunded'), (11, 'On Hold'), (12, 'Returned'), (13, 'Exchange Requested'), (14, 'Completed'), (15, 'Dispute')], default=1),
        ),
    ]
