# Generated by Django 4.1.2 on 2023-03-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_create_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
