# Generated by Django 4.1.2 on 2023-04-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_delete_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
