# Generated by Django 4.1.2 on 2023-04-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_alter_product_description_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("created_at", models.DateField(auto_now=True)),
                (
                    "reason",
                    models.IntegerField(
                        choices=[
                            (0, "CEO purchase"),
                            (1, "Ordered"),
                            (2, "Returned"),
                            (3, "Damaged"),
                        ]
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "Incremental"), (1, "Decremental")]
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
    ]
