# Generated by Django 4.1.2 on 2023-02-11 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0012_alter_orderstatuslog_previous_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatuslog',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
