# Generated by Django 4.1.2 on 2023-02-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_field_performer on_orderstatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Awaiting Fulfillment'), (4, 'Fulfilled'), (5, 'Shipped'), (6, 'Delivered'), (7, 'Cancelled'), (8, 'Refunded'), (9, 'On Hold'), (10, 'Returned'), (11, 'Exchange Requested'), (12, 'Completed')], default=1),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='current_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Awaiting Fulfillment'), (4, 'Fulfilled'), (5, 'Shipped'), (6, 'Delivered'), (7, 'Cancelled'), (8, 'Refunded'), (9, 'On Hold'), (10, 'Returned'), (11, 'Exchange Requested'), (12, 'Completed')], default=1),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='previous_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Awaiting Fulfillment'), (4, 'Fulfilled'), (5, 'Shipped'), (6, 'Delivered'), (7, 'Cancelled'), (8, 'Refunded'), (9, 'On Hold'), (10, 'Returned'), (11, 'Exchange Requested'), (12, 'Completed')], default=0),
        ),
    ]
