# Generated by Django 4.1.2 on 2023-02-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_orderstatuslog_performer_orderstatuslog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'Awaiting Fulfillment'), (3, 'Fulfilled'), (4, 'Shipped'), (5, 'Delivered'), (6, 'Cancelled'), (7, 'Refunded'), (8, 'On Hold'), (9, 'Returned'), (10, 'Exchange Requested'), (11, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='current_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'Awaiting Fulfillment'), (3, 'Fulfilled'), (4, 'Shipped'), (5, 'Delivered'), (6, 'Cancelled'), (7, 'Refunded'), (8, 'On Hold'), (9, 'Returned'), (10, 'Exchange Requested'), (11, 'Completed')]),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='previous_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'Awaiting Fulfillment'), (3, 'Fulfilled'), (4, 'Shipped'), (5, 'Delivered'), (6, 'Cancelled'), (7, 'Refunded'), (8, 'On Hold'), (9, 'Returned'), (10, 'Exchange Requested'), (11, 'Completed')]),
        ),
    ]
